# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('birthDate', models.DateTimeField()),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('telephonePortable', models.CharField(blank=True, max_length=12, null=True)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('codePostal', models.IntegerField()),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('linkedIn', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('Interet', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profil',
            },
        ),
    ]
