# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilApp', '0002_auto_20170511_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='password',
        ),
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='usersPics/no-img.png', upload_to='usersPics/'),
        ),
    ]
