# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilApp', '0003_auto_20170514_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='static/usersPics/no-img.png', upload_to='static/usersPics/'),
        ),
    ]
