# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilApp', '0004_auto_20170514_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='image',
        ),
        migrations.AddField(
            model_name='profil',
            name='imageName',
            field=models.CharField(default='no-image.png', max_length=200),
        ),
    ]
