# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilApp', '0005_auto_20170514_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='imageName',
            field=models.CharField(default='usersPics/no-img.png', max_length=200),
        ),
    ]
